### ISSUE TITLE
semicolon in `type`: Unexpected token has appeared.

### ISSUE THREAD

**Issue by azu** [shellyln/tynder#1]
I've met a error on compiling following schema.

```ts
type O =  {
    a: string;
    b: number;
}
```

tynder compiler said following:

```
parse error occured at position:32  interfaceDefInner: Unexpected token has appeared.
     tring;
          ^~~~~~~~
    b: number;
}
```

This code is valid in TypeScript.

TypeScript allow to use `;` and `,` in the `ObjectType`'s `TypeBody`

<img width="286" alt="image" src="https://user-images.githubusercontent.com/19714/74331180-7d5fec80-4dd6-11ea-853c-8af530dc6a59.png">

- Spec: https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#3.10
- [Playground Link](https://www.typescriptlang.org/play/index.html?ssl=6&ssc=9&pln=6&pc=12#code/C4TwDgpgBA8lC8UoG8CwAoJSCGAuKAzsAE4CWAdgOYDcGWUARvuQK4C2DExt6AvhgGMA9uSJQh+OIjSYseKACJsCgDR0sTKAEYMvIA)

It is good that tynder compile allow to use `;` in the Type alias, I think.

## Reproduce Repository

- https://github.com/azu/tynder-issue-semicolon-in-type

📝  tynder compiler can compile `interface` that use `;` as terminate.

```ts
interface O {
    a: string;
    b: number;
}
```

**Comment by shellyln** [comment]
Hi, @azu !
Thank you for posting the issue.

I'll fix it.

I know, of course, that semicolon is allowed in both cases, but I thought it would be better not to give more than one grammatical choice.
So I allowed only comma for `type` and only semicolon for `interface`.

But the default (preferred) syntax for eslint seems to be a semicolon.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-delimiter-style.md

**Comment by azu** [comment]
I've found this error in developing https://github.com/secretlint/secretlint

1. Create `@secretlint/types` package to collect type interface for TypeScript
2. Create a validator from existing TypeScript code base using tynder
  - https://github.com/secretlint/secretlint/issues/23
3. I try to compile existing TypeScript code(`@secretlint/types`) and get this issue
  - I did run command: `tynder compile --inext ts --indir src --outdir schema/`

So, I've found this issue during creating a schema from existing TypeScript.
My main usecase is that create validator from TypeScript.
Maybe, It is different with tynder main usecase.

**Comment by shellyln** [comment]
Not directly related to this issue's error (but will affect your existing codes), tynder compiler requires a semicolon at the end of the type statement.
(Does not perform "Automatic Semicolon Insertion" (http://www.ecma-international.org/ecma-262/5.1/#sec-7.9)

```ts
type O =  {
    a: string;
    b: number;
} // <- error
```

**Comment by shellyln** [comment]
I've fixed semicolon in `type`.
```ts
type O =  {
    a: string;
    b: number;
};
```

But the following code is still have an error.
```ts
type O =  {
    a: string;
    b: number;
} // <- no semicolon
```

**Comment by azu** [comment]
Thanks.
I'm ok that no support for ASI(Auto Semicolon Insertion).

**Comment by shellyln** [comment]
I've fixed.  Error messages improved in many cases in `v0.1.5`.

```ts
type O =  {
    a: string;
    b: number;
} // <- no semicolon
```

```
Error: parse error occured at position:65  typeDef: Unexpected token has appeared. Expect ";".
     colon
          ^~~~~~~~
```

**Comment by shellyln** [comment]
Hi, @azu !
I think `semicolon in type` has been fixed and reasonable error message is shown.
If you have problems with error messages, etc. Please open new issue.
Thank you!

**Comment by azu** [comment]
Thanks!
